### ISSUE TITLE
关于clash的proxy-providers有点小需求

### ISSUE THREAD

**Issue by xy9860** [tindy2013/subconverter#183]
我在模板里面使用了proxy-providers配置，打算生成一个包含proxy-providers的配置文件，然后clash在去请求proxy-providers里面写的地址。但是第一步生成配置必须要需要提供url参数，如果提供了的话最后生成的配置中就会含有proxies字段。希望能提供选项在完全使用proxy-providers配置的话取消url参数，阻止生成proxies字段。

还有关于group的生成，我使用以下两种格式：
```
group_name`select`!!provider_name
group_name`select`!!GROUP=provider_name
```
都只能得到：
```
- name: group_name
  type: select
  proxies:
    - DIRECT
```
预期的生成结果为：
```
- name: group_name
  type: select
  use:
    - provider_name
```
生成provider的group的正确格式该怎么写？
