### ISSUE TITLE
希望能新增更加安全的插入自定义节点的方式

### ISSUE THREAD

**Issue by GizmoOAO** [tindy2013/subconverter#194]
`common.api_mode`设置为`true`.  
 直接请求`/sub`不带`token`参数也会把`common.insert_url`的节点插入到返回结果里. 

使用`/getprofile`会强制要求携带`token`参数.
但profile文件似乎没有比较好的添加自定义节点的方式.
只能使用下面这种看起来很丑还很不直观的方式添加自定义节点:
```
[Profile]
target=clash
url=https://dler.cloud/subscribe/ABCDE?clash=vmess|ss://YWVzLTEyOC1nY206dGVzdA==@192.168.100.1:8888#Example1
```

希望能新增更加安全的插入自定义节点的方式.
比如让profile文件支持使用yaml, url参数以Array的方式提供
``` yaml
Profile:
  target: clash
  url:
    - https://dler.cloud/subscribe/ABCDE?clash=vmess
    - ss://YWVzLTEyOC1nY206dGVzdA==@192.168.100.1:8888#Example1
```

又或者将`pref`支持的import添加到profile文件中:
```
[Profile]
target=clash
url=https://dler.cloud/subscribe/ABCDE?clash=vmess|!!import:myss.txt
```
