### ISSUE TITLE
请问如何在别人搭建好的站点中订阅Clash配置文件时加入自定义的配置

### ISSUE THREAD

**Issue by walkxspace** [tindy2013/subconverter#221]
想在 [https://acl4ssr.netlify.app/](https://acl4ssr.netlify.app/) 给 Clash for Android 的订阅文件中加入如下的 DNS 配置，但不知道在上传配置的时候应该如何填写，希望能得到好心人指导，感谢。
```
dns:
  enable: true
  ipv6: false
  listen: '0.0.0.0:6553'
  enhanced-mode: fake-ip
  default-nameserver:
    - 117.50.11.11
    - 52.80.66.66
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
  nameserver:
    - 'https://dns.cloudflare.com/dns-query'
    - 'https://dns.google/dns-query'
    - 'https://dns.adguard.com/dns-query'
```
