### ISSUE TITLE
clash转换成surfboard时ws-path缺少后半Edge信息

### ISSUE THREAD

**Issue by aflyhorse** [tindy2013/subconverter#290]
其实为什么是这样我也不是很明白……
我在v2ray-core和clash的github repo里搜索Edge关键字，都没有找到有意义的代码

Clash配置节选：
```
proxies:
  - name: NAME_HERE
    type: vmess
    server: SERVER_HERE
    port: 80
    uuid: "UUID_HERE"
    alterId: 32
    cipher: none
    udp: true
    network: ws
    ws-path: "/t"
    ws-headers: { "Host":"api.apple.com", "Edge": "www.example.com:88888" }
    headers: {"Host":"api.apple.com", "Edge": "www.example.com:88888" }
    tls: false
```

用 subconverter 转换出的配置：
```
NAME_HERE = vmess, SERVER_HERE, 80, username=UUID_HERE, tls=false, ws=true, ws-path=/t, sni=api.apple.com, ws-headers=Host:api.apple.com|Edge:www.example.com:88888, udp-relay=true
```

询问机场客服，以及实测导入到surfboard时能用的配置：
```
NAME_HERE = vmess, SERVER_HERE, 80, username=UUID_HERE, tls=false, ws=true, ws-path=/s/www.example.com:88888, sni=api.apple.com, ws-headers=Host:api.apple.com|Edge:www.example.com:88888, udp-relay=true
```

区别就是ws-path的/t被替换成了/s，再加上了Edge字段的内容
同时，在整个Clash配置里全文搜索，没有/s字样（所以很玄学啊）

以上字段已脱敏，Contributor可以私我拿个地址做测试
