### ISSUE TITLE
最新版本转换vmess时alterId被错误转换为16进制数

### ISSUE THREAD

**Issue by zhongfly** [tindy2013/subconverter#325]
原始订阅如下：
```
  -
    name: 'HK'
    type: vmess
    server: ……
    port: ……
    uuid: ……
    alterId: 16
    cipher: auto
    udp: true
    network: ws
    ws-path: /awshk01
    ws-headers:
      Host: ……
```
转换后，
```
  - {name: "HK", server: ……, port: ……, type: vmess, uuid: ……, alterId: "\x10", cipher: auto, tls: false, network: ws, ws-path: /awshk01, ws-headers: {Host: ……}}
```
alterId变为十六进制数\x10
同一订阅中alterId原本为2的，转换后变为\x02
