### ISSUE TITLE
Argument scv not working

### ISSUE THREAD

**Issue by elvizlai** [tindy2013/subconverter#336]
Example:
```
docker run -itd \
  --restart always \
  --name subconverter \
  -p 127.0.0.1:25500:25500 \
  tindy2013/subconverter
```

Curl test case
```
curl "http://127.0.0.1:25500/sub?target=v2ray&scv=true&tfo=true&url=https%3A%2F%2Ftor-acc-tx.HIDDEN.xyz%3A6443%2Fv2ray%2Fxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx"
```
try using shadowrockts to sub, but config `skip-cert-verify` is false, which is not working as expected.

The source url proxy example:
```
  - name: "美国"
    type: vmess
    server: xxx.xxx.xxx.xxx
    port: 443
    uuid: "{{USERID}}"
    alterId: 16
    cipher: auto
    network: ws
    ws-path: "/hidden/"
    ws-headers:
      Host: abc.aabbccdd.com
    tls: true
    skip-cert-verify: true
    udp: true
```
