### ISSUE TITLE
Trojan ws 订阅转换后丢失 network 参数

### ISSUE THREAD

**Issue by reizhi** [tindy2013/subconverter#431]
根据 Clash [所提供的](https://github.com/Dreamacro/clash/wiki/configuration) Trojan ws 配置样本：
````
  - name: trojan-ws
    server: server
    port: 443
    type: trojan
    password: "example"
    network: ws
    udp: true
    ws-opts:
      path: /path
      headers:
        Host: example.com
````
由上游所给出的订阅，转换类型选择 Clash 后，结果为：
`- {name: "trojan-ws", server: server, port: 443, type: trojan, password: example, skip-cert-verify: true, ws-opts: {path: /path}, udp: true}`

可见 network 参数丢失，导致无法连接，而源订阅则可以正常连接。
