### ISSUE TITLE
[BUG] v0.7.1-217891f转换时候ws-opt丢了servername参数?

### ISSUE THREAD

**Issue by vj23456** [tindy2013/subconverter#449]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

0.7.1-217891f

### 转换过程

Clash转换为clash

### 转换设置

https://sub.xeton.dev/sub?target=clash&new_name=true&url=https**************&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online.ini

### 复现步骤

原配置文件为

```
- name: 123456
    type: vmess
    server: XXXXX.com
    port: 3331
    uuid: "57e0cb4d-eae5-48ec-8091-1XXXXXXX"
    alterId: 0
    cipher: chacha20-poly1305
    udp: true
    network: ws
    ws-path: "/t"
    ws-headers: { "Host":"tls.apple.com", "Edge": "12a00c4.fm.huawei.com:82897" }
    ws-opts:
      path: "/t"
      headers: { "Host":"tls.apple.com", "Edge": "12a00c4.fm.huawei.com:82897" }
    headers: {"Host":"tls.apple.com", "Edge": "12a00c4.fm.huawei.com:82897" }
    servername: n2.XXXXXX.com
    tls: true
```

    
    
转换后为
    
```- {name: 123456, server:  XXXXX.com, port: 3331, type: vmess, uuid: 57e0cb4d-eae5-48ec-8091-1XXXXXXX, alterId: 0, cipher: chacha20-poly1305, tls: true, network: ws, ws-opts: {path: /t, headers: {Host: tls.apple.com, Edge: 12a00c4.fm.huawei.com:82897}}, udp: true}```
      
      
丢了 servername: n2.XXXXXX.com  导致节点不通

### 期望结果

详看复现步骤

### 实际结果

详看复现步骤
