### ISSUE TITLE
[BUG] 转换后配置文件缺少tolerance参数

### ISSUE THREAD

**Issue by exlulu** [tindy2013/subconverter#461]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

v0.7.1-80cda7b

### 转换过程

机场订阅转CLASH

### 转换设置

pref.toml，默认，所有文件都没有改动

### 复现步骤

> http://127.0.0.1:25500/sub?target=clash&url=URLEncode订阅地址&insert=false&emoji=true&list=false&tfo=false&scv=false&fdn=false&sort=false&udp=true&new_name=true&config=https%3A%2F%2Fgithub.com%2FACL4SSR%2FACL4SSR%2Fraw%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online_Full.ini

正常转换就能复现，如果使用[Releases v0.7.1](https://github.com/tindy2013/subconverter/releases/tag/v0.7.1)，转换后的配置文件是带有tolerance参数的，用v0.7.1-80cda7b转换后的配置就没了tolerance参数

### 期望结果

  - name: ♻️ 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - aaa
      - bbb

### 实际结果

  - name: ♻️ 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - aaa
      - bbb

**Comment by zhongfly** [comment]
应该提供具体的转换配置

经过我的测试，在v0.7.1-80cda7b上使用ini格式的外部配置会使得tolerance参数丢失
例如：https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/config/ACL4SSR_Online.ini
或者按以下外部配置测试：
```ini
enable_rule_generator=true
overwrite_original_rules=true
ruleset=自动选择,[]FINAL
custom_proxy_group=自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50
```

若使用toml格式的配置就不会出现此问题：
```toml
version = 1
[custom]
enable_rule_generator = true
overwrite_original_rules = true

[[custom_groups]]
name = "自动选择"
type = "url-test"
rule = [".*"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 50

[[rulesets]]
group = "自动选择"
ruleset = "[]FINAL"
```
