### ISSUE TITLE
[BUG] 转换订阅后缺失 Header 字段

### ISSUE THREAD

**Issue by imbytecat** [tindy2013/subconverter#465]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

~0.7.1~
经提醒修改为：Docker 镜像：[tindy2013/subconverter:latest](https://hub.docker.com/layers/tindy2013/subconverter/latest/images/sha256-ec64895f7ddbc4456f787e7e22afa862824f230ca17484d9601c83df5ea4ab35?context=explore)

### 转换过程

使用 v2ray 的 vmess + ws 模式，自定义 headers 中的 cookie 选项

### 转换设置

```
  - name: China 01
    type: vmess
    server: example.com
    port: 443
    uuid: 1145144a-8c7c-4020-81b8-1d4421919810
    alterId: 0
    cipher: auto
    udp: true
    tls: true
    network: ws
    ws-opts:
      path: /ws114514/
      headers:
        Host: example.com
        Cookie: 'token=1145141919810'
```

### 复现步骤

订阅转换后只有 Host 字段，而没有 Cookie 字段

### 期望结果

可以支持 Headers 自定义的所有字段，尤其是 Cookie 字段

### 实际结果

订阅转换后只有 Host 字段，而没有 Cookie 字段
