### ISSUE TITLE
[BUG] <外部配置为yml出现问题>

### ISSUE THREAD

**Issue by xqXQzzz1** [tindy2013/subconverter#466]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

subconverter v0.7.1-80cda7b backend

### 转换过程

正常转换

### 转换设置

``` yaml
custom:
  enable_rule_generator: true
  overwrite_original_rules: true
  proxy_groups:
    # - {name: UrlTest, type: url-test, rule: ['.*'], url: http://www.gstatic.com/generate_204, interval: 300, tolerance: 100, timeout: 5}
    # - {name: Proxy, type: select, rule: ['.*']}
    # - {name: group1, type: select, rule: ['!!GROUPID=0']}
    # - {name: v2ray, type: select, rule: ['!!GROUP=V2RayProvider']}
    # - {import: snippets/groups_forcerule.txt}
    # - {name: ssid group, type: ssid, rule: ['default_group', 'celluar=group0,ssid1=group1,ssid2=group2']}
    # - {import: snippets/groups.txt}
    - {
        name: ♻️ 自动选择,
        type: url-test,
        rule: ["♻️ 自动选择", "DIRECT", "^(?!(解锁节点|.*NetEase)).*$"],
        url: http://www.gstatic.com/generate_204,
        interval: 300,
        tolerance: 100,
        timeout: 5,
      }
    - {
        name: 🚀 节点选择,
        type: select,
        rule: ["♻️ 自动选择", "DIRECT", ".*IPLC.*", "^(?!(.*IPLC)).*$"],
      }
    - {
        name: 🌍 国外媒体,
        type: select,
        rule:
          [
            "♻️ 自动选择",
            "🚀 节点选择",
            "DIRECT",
            ".*IPLC.*",
            "^(?!(.*IPLC)).*$",
          ],
      }
    - {
        name: 📲 社交软件,
        type: select,
        rule:
          [
            "♻️ 自动选择",
            "🚀 节点选择",
            "DIRECT",
            ".*IPLC.*",
            "^(?!(.*IPLC)).*$",
          ],
      }
    - {
        name: 🐟 漏网之鱼,
        type: select,
        rule: ["DIRECT", "🚀 节点选择", ".*IPLC.*", "^(?!(.*IPLC)).*$"],
      }
    # - { name: 🆎 广告净化, type: select, rule: ["♻️ 自动选择", "🚀 节点选择", "DIRECT", ".*IPLC.*", "^(?!(.*IPLC)).*$", ] }
    # - { name: 🔒 隐私防护, type: select, rule: ["♻️ 自动选择", "🚀 节点选择", "DIRECT", ".*IPLC.*", "^(?!(.*IPLC)).*$", ] }
    - {
        name: 🎮 游戏论坛,
        type: select,
        rule:
          [
            "♻️ 自动选择",
            "🚀 节点选择",
            "DIRECT",
            ".*IPLC.*",
            "^(?!(.*IPLC)).*$",
          ],
      }
    - { name: 🎮 游戏代理, type: select, rule: ["DIRECT", ".*IPLC.*"] }
    - {
        name: 🎮 游戏论坛,
        type: select,
        rule:
          [
            "♻️ 自动选择",
            "🚀 节点选择",
            "DIRECT",
            ".*IPLC.*",
            "^(?!(.*IPLC)).*$",
          ],
      }
    - {
        name: 🧱 砖块代理,
        type: select,
        rule:
          [
            "♻️ 自动选择",
            "🚀 节点选择",
            "DIRECT",
            ".*IPLC.*",
            "^(?!(.*IPLC)).*$",
          ],
      }
    - {
        name: Ⓜ️ 微软云盘,
        type: select,
        rule:
          [
            "♻️ 自动选择",
            "🚀 节点选择",
            "DIRECT",
            ".*IPLC.*",
            "^(?!(.*IPLC)).*$",
          ],
      }
    - {
        name: 📢 谷歌FCM,
        type: select,
        rule:
          [
            "♻️ 自动选择",
            "🚀 节点选择",
            "DIRECT",
            ".*IPLC.*",
            "^(?!(.*IPLC)).*$",
          ],
      }
  rulesets:
    # ;Ruleset addresses, supports local files/URL
    # ;Format: Group name,[type:]URL[,interval]
    # ;        Group name,[]Rule
    # ;where 'type' supports the following value: surge, quanx, clash-domain, clash-ipcidr, clash-classic
    # ;type defaults to surge if omitted
    #  - {import: snippets/ruleset_remote.txt}
    # - {rule: 'GEOIP,CN', group: 'DIRECT'}
    # - {ruleset: 'rules/LocalAreaNetwork.list', group: 'DIRECT'}
    # - {ruleset: 'surge:rules/LocalAreaNetwork.list', group: 'DIRECT'}
    # - {ruleset: 'quanx:https://raw.staticdn.net/ConnersHua/Profiles/master/Quantumult/X/Filter/Advertising.list', group: 'Advertising', interval: 86400}
    # - {ruleset: 'clash-domain:https://ruleset.dev/clash_domestic_services_domains', group: 'Domestic Services', interval: 86400}
    # - {ruleset: 'clash-ipcidr:https://ruleset.dev/clash_domestic_services_ips', group: 'Domestic Services', interval: 86400}
    # - {ruleset: 'clash-classic:https://raw.staticdn.net/DivineEngine/Profiles/master/Clash/RuleSet/China.yaml', group: 'DIRECT', interval: 86400}
    # - {import: snippets/groups_forcerule.txt}
    - {
        ruleset: "clash-classic:https://raw.fastgit.org/xqXQzzz1/clashpref/main/own/owngame.yaml",
        group: "🎮 游戏代理",
        interval: 43200,
      }
    - {
        ruleset: "clash-classic:https://raw.fastgit.org/xqXQzzz1/clashpref/main/own/owngamecom.yaml",
        group: "🎮 游戏论坛",
        interval: 43200,
      }
    - {
        ruleset: "clash-classic:https://raw.fastgit.org/xqXQzzz1/clashpref/main/own/own.yaml",
        group: "🧱 砖块代理",
        interval: 43200,
      }
    - {
        ruleset: "clash-classic:https://raw.fastgit.org/xqXQzzz1/clashpref/main/own/ownban.yaml",
        group: "REJECT",
        interval: 43200,
      }
    - {
        ruleset: "clash-classic:https://raw.fastgit.org/xqXQzzz1/clashpref/main/own/owndirect.yaml",
        group: "DIRECT",
        interval: 43200,
      }
    - {
        ruleset: "clash-classic:https://raw.fastgit.org/xqXQzzz1/clashpref/main/own/ownmedia.yaml",
        group: "🌍 国外媒体",
        interval: 43200,
      }
    - {
        ruleset: "clash-classic:https://raw.fastgit.org/xqXQzzz1/clashpref/main/own/ownproxy.yaml",
        group: "🚀 节点选择",
        interval: 43200,
      }
    - {
        ruleset: "clash-classic:https://raw.fastgit.org/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.yaml",
        group: "DIRECT",
        interval: 43200,
      }
    # - {
    #     ruleset: "clash-classic:https://raw.fastgit.org/blackmatrix7/ios_rule_script/master/rule/Clash/SteamCN/SteamCN.yaml",
    #     group: "DIRECT",
    #     interval: 43200,
    #   }
    # - {
    #     ruleset: "clash-classic:https://raw.githubusercontents.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Steam.yaml",
    #     group: "🎮 游戏论坛",
    #     interval: 43200,
    #   }
    - {
        ruleset: "https://raw.githubusercontent.com/AoEiuV020/SubConfig/main/steam-direct.list",
        group: "DIRECT",
        interval: 43200,
      }
    - {
        ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list",
        group: "DIRECT",
        interval: 43200,
      }
    - {
        ruleset: "https://raw.githubusercontent.com/AoEiuV020/SubConfig/main/steam-proxy.list",
        group: "🎮 游戏论坛",
        interval: 43200,
      }
    - {
        ruleset: "clash-classic:https://raw.fastgit.org/blackmatrix7/ios_rule_script/master/rule/Clash/OneDrive/OneDrive.yaml",
        group: "Ⓜ️ 微软云盘",
        interval: 43200,
      }
    # - {
    #     ruleset: "clash-domain:https://raw.fastgit.org/blackmatrix7/ios_rule_script/master/rule/Clash/Privacy/Privacy_Domain.yaml",
    #     group: "🔒 隐私防护",
    #     interval: 43200
    #   }
    # - {
    #     ruleset: "clash-classic:https://raw.fastgit.org/blackmatrix7/ios_rule_script/master/rule/Clash/AdvertisingLite/AdvertisingLite.yaml",
    #     group: "🆎 广告净化",
    #     interval: 43200
    #   }
    # - {
    #     ruleset: "clash-domain:https://raw.fastgit.org/blackmatrix7/ios_rule_script/master/rule/Clash/AdvertisingLite/AdvertisingLite_Domain.yaml",
    #     group: "🆎 广告净化",
    #     interval: 43200
    # }
    - {
        ruleset: "clash-classic:https://raw.githubusercontents.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/GoogleFCM.yaml",
        group: "📢 谷歌FCM",
        interval: 43200,
      }
    - {
        ruleset: "clash-classic:https://raw.fastgit.org/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Porn.yaml",
        group: "🌍 国外媒体",
        interval: 43200,
      }
    - {
        ruleset: "clash-classic:https://raw.fastgit.org/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia.yaml",
        group: "🌍 国外媒体",
        interval: 43200,
      }
    - {
        ruleset: "clash-classic:https://raw.fastgit.org/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml",
        group: "📲 社交软件",
        interval: 43200,
      }
    - {
        ruleset: "https://raw.fastgit.org/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.yaml",
        group: "📲 社交软件",
        interval: 43200,
      }
    - {
        ruleset: "https://raw.fastgit.org/blackmatrix7/ios_rule_script/master/rule/Clash/Instagram/Instagram.yaml",
        group: "📲 社交软件",
        interval: 43200,
      }
    - {
        ruleset: "https://raw.fastgit.org/blackmatrix7/ios_rule_script/master/rule/Clash/Facebook/Facebook.yaml",
        group: "📲 社交软件",
        interval: 43200,
      }
    - {
        ruleset: "clash-classic:https://raw.fastgit.org/blackmatrix7/ios_rule_script/master/rule/Clash/Proxy/Proxy_Classical.yaml",
        group: "🚀 节点选择",
        interval: 43200,
      }
    - {
        ruleset: "clash-classic:https://raw.fastgit.org/blackmatrix7/ios_rule_script/master/rule/Clash/China/China.yaml",
        group: "DIRECT",
        interval: 43200,
      }
    - { rule: "GEOIP,CN", group: "DIRECT" }
    - { rule: "MATCH", group: "🐟 漏网之鱼" }

  clash_rule_base: https://raw.githubusercontent.com/xqXQzzz1/clashpref/main/base/all_base.tpl
  #  surge_rule_base: https://raw.githubusercontent.com/xqXQzzz1/clashpref/main/base/surge.conf
  #  surfboard_rule_base: base/surfboard.conf
  #  mellow_rule_base: base/mellow.conf
  #  quan_rule_base: base/quan.conf
  #  quanx_rule_base: base/quanx.conf

  #  rename_node:
  #  - {import: snippet/rename.txt}

  #  add_emoji: true
  #  remove_old_emoji: true
  #  emojis:
  #  - {import: snippets/emoji.txt}

  #  include_remarks: []
  exclude_remarks:
    [
      '^(?=(\d\d\.|(I\+?|E\+?|G\+?|H\+?)\.)).*$',
      '^.*解锁.*\(本地\).*$',
      "^.*(收费请举报).*$",
    ]
  template_args:
    #     ; variables in the local scope
    # ; 从 配置文件 中获取，判断前缀为 global
    # ; 从 外部配置 中获取，判断前缀为 local
    # ; 从 URL 链接中获取，判断前缀为 request，例如 http://127.0.0.1:25500/sub?target=clash&url=www.xxx.com&clash.dns=1
    - { key: clash.mixed_port, value: 7890 }
    - { key: clash.allow_lan, value: false }
    - { key: clash.log_level, value: info }
```

### 复现步骤

使用yml格式的外部配置。

### 期望结果

正常转换

### 实际结果

Template render failed! Reason: [inja.exception.render_error] (at 9:18) variable 'local.clash.mixed_port' not found
