### ISSUE TITLE
[BUG] TOML 配置文件生成错误的 Surge 配置

### ISSUE THREAD

**Issue by gouku** [tindy2013/subconverter#474]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

0.7.2

### 转换过程

通过profile将list输出成surge配置

### 转换设置

groups.toml:

```toml
[[custom_groups]]
name = "负载均衡节点"
type = "load-balance"
rule = ["^(?!.*(中国|CN)).*"] # 排除所有国内节点
url = "http://www.gstatic.com/generate_204"
interval = 150
tolerance = 120
strategy = "round-robin"
```

### 复现步骤

参考上面的配置

### 期望结果

Surge 版本可以正常输出 load-balance 节点结果：

```
auto-lb = load-balance,节点1,节点2,节点99,url=http://www.gstatic.com/generate_204,interval=150,tolerance=120
```

### 实际结果

Surge 配置的输出结果为：

```
负载均衡= load-balance,default=^(?!.*(中国|CN)).*,
```

而 Clash 就可以输出正确结果：

```yaml
  - name: 负载均衡
    type: load-balance
    strategy: round-robin
    url: http://www.gstatic.com/generate_204
    interval: 150
    proxies:
      - "节点1"
      - "节点2"
      - "节点999"
```

### 错误信息

```shell
没有报错：


subconverter  | 2022/04/08 Fri 15:23:38.209896 [1 281472803240696][INFO] Trying to load profile 'profiles/test.ini'.
subconverter  | 2022/04/08 Fri 15:23:38.210007 [1 281472803240696][INFO] Trying to parse profile 'profiles/test.ini'.
subconverter  | 2022/04/08 Fri 15:23:38.210060 [1 281472803240696][INFO] Loading preference settings...
subconverter  | 2022/04/08 Fri 15:23:38.236469 [1 281472803240696][INFO] Load preference settings in TOML format completed.
subconverter  | 2022/04/08 Fri 15:23:38.237045 [1 281472803240696][INFO] Fetching node data from url 'xxx'.
subconverter  | 2022/04/08 Fri 15:23:38.589347 [1 281472803240696][INFO] Fetching node data from url 'xxx'.
subconverter  | 2022/04/08 Fri 15:23:40.130695 [1 281472803240696][INFO] Fetching node data from url 'xxx'.
subconverter  | 2022/04/08 Fri 15:23:52.766926 [1 281472803240696][INFO] Generate target: Surge 4
subconverter  | 2022/04/08 Fri 15:23:52.782978 [1 281472803240696][INFO] Generate completed.
```
```
