### ISSUE TITLE
[Feature] pref.yml中，default_url的使用方法

### ISSUE THREAD

**Issue by sunjx97** [tindy2013/subconverter#515]
### verify

- [X] 我已经仔细阅读[项目文档](https://github.com/tindy2013/subconverter/blob/master/README-cn.md)，确认现有功能无法解决我的需求
- [X] 我已经检索过现有[issue](https://github.com/tindy2013/subconverter/issues)，确认与现有issue的内容并不重复
- [ ] 我已经尝试自行解决，确认自己没有能力解决

### 功能描述

在编写 pref.yml 文件时，default_url的value是一个列表，里面 `tag:mytag,链接` 这样的形式是可以的，如下所示。
```
common:
  # API 模式，设置为 true 以防止直接加载本地订阅或直接提供本地文件，若访问这些内容则需要接上 &token=。（多用于部署公共订阅转换服务时）
  api_mode: false
  # 无 %URL% 参数时，默认加载的订阅链接， 不需要 URLEncode。
  default_url: 
    - "tag:mytag,xxx"
    - "tag:mytag,xxx"
```

我想知道除了以整体字符串的形式外，还有没有别的写法（如字典），感觉现在这样可读性会更好些。
~~如果只是我没找到，麻烦发下链接，谢谢！~~

另外，yml格式的pref文件写法样例好像有点少，希望能补充orz。

### 可能的解决方案

使用字典形式，如下。
```
common:
  # API 模式，设置为 true 以防止直接加载本地订阅或直接提供本地文件，若访问这些内容则需要接上 &token=。（多用于部署公共订阅转换服务时）
  api_mode: false
  # 无 %URL% 参数时，默认加载的订阅链接， 不需要 URLEncode。
  default_url: 
    - {tag: mytag, url: xxx}
    - {tag: mytag, url: xxx}
```
