### ISSUE TITLE
not support v2fly vmess websocket 0rtt 

### ISSUE THREAD

**Issue by likedidu** [tindy2013/subconverter#556]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

ALL

### 转换过程

clash 2 clash

### 转换设置

```
# for v2fly and xray (recommand)
- name: "vmess-ws-0rtt"
  type: vmess
  server: server
  port: 443
  uuid: uuid
  alterId: 32
  cipher: auto
  network: ws
  ws-opts:
    path: /
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol
```

### 复现步骤

自己维护的一份 proxies node list  尝试使用 subconverter 转换成按国家区分的 proxy providers 发现关于 vmess websocket 0rtt 的两个字段并没有显示出来 代码中解析 clash 订阅对于 ws 的部分 好像并没有这两个字段

### 期望结果

```
- name: "vmess-ws-0rtt"
  type: vmess
  server: server
  port: 443
  uuid: uuid
  alterId: 32
  cipher: auto
  network: ws
  ws-opts:
    path: /
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol
```

### 实际结果

```
- name: "vmess-ws-0rtt"
  type: vmess
  server: server
  port: 443
  uuid: uuid
  alterId: 32
  cipher: auto
  network: ws
  ws-opts:
    path: /
```

### 错误信息

```shell
.......
```
