### ISSUE TITLE
[BUG] config 中 template 的变量无法使用local.variable获取到

### ISSUE THREAD

**Issue by OIIvIIO** [tindy2013/subconverter#577]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

0.7.2

### 转换过程

订阅转为surge配置

### 转换设置

调用链接：http://127.0.0.1:25500/sub?target=surge&ver=4&url=%URL%&config=config%2Fsurge.yml

base/surge.conf 添加以下内容
```
[General]

[Proxy]

[Remote Proxy]

[Proxy Group]

[Rule]

[Remote Rule]

[Remote Rewrite]

[MITM]
{% if exists("local.surge.MITM.test") %}
test = {{ local.surge.MITM.test }}
{% endif %}
```

config/config.yml
```yml
custom:
  enable_rule_generator: true
  overwrite_original_rules: true

  proxy_groups:
  - {import: snippets/groups_forcerule.txt}

  rulesets:
  - {import: snippets/rulesets_remote.txt}

  clash_rule_base: base/forcerule.yml
  surge_rule_base: base/surge.conf
#  surfboard_rule_base: base/surfboard.conf
#  mellow_rule_base: base/mellow.conf
#  quan_rule_base: base/quan.conf
#  quanx_rule_base: base/quanx.conf

  rename_node:
  - {import: snippets/rename_node.txt}

  add_emoji: true
  remove_old_emoji: true
  emojis:
  - {import: snippets/emoji.txt}

#  include_remarks: []
#  exclude_remarks: []
  template_args:
  - {key: surge.MITM.test, value: test}
```

### 复现步骤

按照转换配置，调用http://127.0.0.1:25500/sub?target=surge&ver=4&config=config%2Fsurge.yml

### 期望结果

```
[General]

[Proxy]

[Remote Proxy]

[Proxy Group]

[Rule]

[Remote Rule]

[Remote Rewrite]

[MITM]
test = test
```

### 实际结果

```
[General]

[Proxy]

[Remote Proxy]

[Proxy Group]

[Rule]

[Remote Rule]

[Remote Rewrite]

[MITM]
```

### 错误信息

```shell
log 中没有相关错误信息。

将config/surge.yml换成config/surge.ini文件，可获取期望结果。

以上在 Windows 64 版和 docker 版复现。
```
