### ISSUE TITLE
[Feature] 每个ruleset单独设置expand

### ISSUE THREAD

**Issue by Xinyu-Wu-0000** [tindy2013/subconverter#578]
### verify

- [X] 我已经仔细阅读[项目文档](https://github.com/tindy2013/subconverter/blob/master/README-cn.md)，确认现有功能无法解决我的需求
- [X] 我已经检索过现有[issue](https://github.com/tindy2013/subconverter/issues)，确认与现有issue的内容并不重复
- [X] 我已经尝试自行解决，确认自己没有能力解决

### 功能描述

从远端拉取的ruleset可以不用expand，生成rule-expand，但本地文件的ruleset则需要expand，希望expand设置可以根据每个ruleset的不同单独设置。

### 可能的解决方案

```yaml  
rulesets:
    - {
        ruleset: "clash-ipcidr:https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt",
        group: "DIRECT",
        interval: 21600,
       expand: false,
      }
    - {
        ruleset: "clash-domain:rules/vscode.yaml",
        group: "Proxy",
        expand: true,
      }
```
