### ISSUE TITLE
[BUG] toml配置文件无法把provider加入代理组

### ISSUE THREAD

**Issue by ericsyj** [tindy2013/subconverter#580]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

0.7.2

### 转换过程

生成clash配置

### 转换设置

[[custom_groups]]
name = "🚀 手动切换"
type = "select"
rule = [".*", "!!PROVIDER=aws", "[]DIRECT", "[]REJECT"]

### 复现步骤

使用toml格式的外部配置生成clash订阅时，已经在配置文件中声明了需要引用proxy-provider，但是在最后的配置文件中并没有生成对应的use字段和代理组名称。

### 期望结果

正常生成对应的use字段和代理组名称

### 实际结果

使用toml格式的外部配置生成clash订阅时，已经在配置文件中声明了需要引用proxy-provider，但是在最后的配置文件中并没有生成对应的use字段和代理组名称。

**Comment by Explorare** [comment]
遇到了同样的问题，我尝试从 `groups_forcerule.toml` 引入如下规则
```
  - name: Wireguard
    type: select
    interface-name: wg
    proxies:
      - DIRECT
  - name: ZeroTier
    type: select
    interface-name: ZeroTier One [uuid]
    proxies:
      - DIRECT
```
用 ini 或者 txt 格式不支持 `interface-name` 参数，必须用 yml 或 toml 才能支持新参数。但在其它配置不变的情况下，`groups_forcerule.txt` 可正确引入内容，`groups_forcerule.toml` 则没有效果，也没有报错，输出的 `proxy-groups:` 是空白。

**Comment by Explorare** [comment]
今日尝试用 toml 格式 config，读取 yml 格式的 base，插入 groups_forcerule.toml
```
[[custom_groups]]
name = "Wireguard"
type = "select"
interface-name = "wg"
rule = ["[]DIRECT"]
```
输出结果如下
```
proxy-groups:
  - name: Wireguard
    type: select
    proxies:
      - DIRECT
```
缺少一个 `interface-name` 参数。
期望输出：
```
proxy-groups:
  - name: Wireguard
    type: select
    interface-name: wg
    proxies:
      - DIRECT
```
