### ISSUE TITLE
[BUG] 启用订阅缓存时，响应头`subscription-userinfo`返回不正确导致 clash 显示流量信息为`1.0B`

### ISSUE THREAD

**Issue by devioa** [tindy2013/subconverter#625]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

v0.7.2

### 转换过程

base64 to clash

### 转换设置

```
advanced:
  log_level: info
  print_debug_info: false
  max_pending_connections: 10240
  max_concurrent_threads: 16
  max_allowed_rulesets: 0
  max_allowed_rules: 0
  max_allowed_download_size: 0
  enable_cache: true
  cache_subscription: 120
  cache_config: 300
  cache_ruleset: 86400
  script_clean_context: true
  async_fetch_ruleset: true
  skip_failed_links: true
```

### 复现步骤

我在 cache 目录里是看到有缓存响应头的，但实际上在返回缓存的订阅信息时
最终返回的`subscription-userinfo`字段值却是`upload=0; download=1; total=1`，导致 clash 显示流量信息为`1.0B`
![QQ截图20230715124001](https://github.com/tindy2013/subconverter/assets/38558065/f7659a3b-584c-4c04-9f35-0b2710a1f33c)
![QQ截图20230715123606](https://github.com/tindy2013/subconverter/assets/38558065/72c6c0ea-2734-4e1f-936e-2a30a2f6c5fb)

### 期望结果

在命中订阅缓存时，`subscription-userinfo`返回正确的字段值，以便 clash 能获得正确的流量信息

### 实际结果

返回了缓存的订阅信息，但是`subscription-userinfo`的 header 字段值不正确，导致 clash 显示流量信息为`1.0B`

### 错误信息

```shell
n/a
```
