### ISSUE TITLE
[BUG] 本地生成 expand=false 不生效

### ISSUE THREAD

**Issue by VirgilChen97** [tindy2013/subconverter#646]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

0.8.1

### 转换过程

本地生成

### 转换设置

generate.ini:
```
[home]
path=/mnt/user/appdata/common_config/clash/generated/home.conf
target=clash
new_name=true
config=http://config.ho.me/subconverter_config.ini
expand=false
url=xxxxx
```

subconverter_config.ini
```
[custom]
custom_proxy_group=自定义直连规则`select`a^`[]出口代理`[]直连规则`[]DIRECT
custom_proxy_group=默认规则`select`a^`[]出口代理`[]直连规则
custom_proxy_group=直连规则`select`a^`[]出口代理`[]DIRECT{% if default(request.is_out, "0") == "1" %}`[]回家{% endif %}

custom_proxy_group=出口代理`select`a^`[]花云低倍率自动择优`[]花云自动择优`[]备用自动择优
{% if default(request.is_out, "0") == "1" %}
custom_proxy_group=回家`select`!!GROUPID=0`[]DIRECT
{% endif %}
custom_proxy_group=美国`select`(us|美国)
custom_proxy_group=俄罗斯`select`(ru|RU|俄罗斯)
custom_proxy_group=花云低倍率自动择优`url-test`!!GROUP=flowercloud!!(.*实验性.*)`http://www.google.com/generate_204`60,5,500
custom_proxy_group=花云自动择优`url-test`!!GROUP=flowercloud!!(^(?!.*(Traffic|Expire)).*)`http://www.google.com/generate_204`60,5,500
custom_proxy_group=备用自动择优`url-test`!!GROUP=backup!!(^(?!.*(25|订阅|一元|5倍|域名|Lv.1|流量|套餐)).*)`http://www.google.com/generate_204`60,5,500

enable_rule_generator=true
overwrite_original_rules=true
{% if default(request.is_out, "0") == "1" %}
ruleset=回家,[]DOMAIN-SUFFIX,ho.me
ruleset=回家,[]IP-CIDR,10.0.0.0/24
{% endif %}
ruleset=DIRECT,clash-ipcidr:http://config.ho.me/rules/remote_rules/lancidr.txt,86400
ruleset=美国,[]DOMAIN-KEYWORD,openai
ruleset=美国,[]DOMAIN-KEYWORD,bard.google.com
ruleset=俄罗斯,[]DOMAIN-KEYWORD,shadowcore
ruleset=自定义直连规则,clash-classic:http://config.ho.me/rules/custom_direct.txt,86400
ruleset=出口代理,clash-classic:http://config.ho.me/rules/custom_proxy.txt,86400
ruleset=REJECT,clash-classic:http://config.ho.me/rules/custom_reject.txt,86400
ruleset=出口代理,clash-domain:http://config.ho.me/rules/remote_rules/proxy.txt,86400
ruleset=出口代理,clash-domain:http://config.ho.me/rules/remote_rules/gfw.txt,86400
ruleset=直连规则,clash-domain:http://config.ho.me/rules/remote_rules/direct.txt,86400
ruleset=直连规则,clash-ipcidr:http://config.ho.me/rules/remote_rules/cncidr.txt,86400
ruleset=直连规则,[]GEOIP,CN
ruleset=默认规则,[]MATCH
```

pref.yml
```
common:
  clash_rule_base: http://config.ho.me/clash/clash_base_rule.yaml
  quanx_rule_base: http://config.ho.me/quanx/quanx_base.conf

node_pref:
  udp_flag: true

server:
  listen: 0.0.0.0

advanced:
  log_level: debug
  print_debug_info: true
  max_allowed_download_size: 0
  max_allowed_rulesets: 0
  max_allowed_rules: 0
  async_fetch_ruleset: true
  enable_cache: true
  cache_config: 0
  cache_ruleset: 0
  cache_subscription: 5
```

### 复现步骤

使用上述配置，进行 `subconverter -g` 本地生成

### 期望结果

规则应该生成为 rule-provider

### 实际结果

规则直接全部生成在配置文件中了
