### ISSUE TITLE
[BUG] clash parse缺少部分配置

### ISSUE THREAD

**Issue by SplitGemini** [tindy2013/subconverter#648]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

0.8.1

### 转换过程

clash转换clash

### 转换设置

不重要

### 复现步骤

clash 配置出现一下结构
```yaml
proxies:
	type: ss
	plugin: v2ray-plugin
	plugin-opts:
	  headers:
	    edge: xxx
```

### 期望结果

补上缺少的字段

### 实际结果

缺少headers:内容

### 错误信息

```shell
根据 [Configuration Reference](https://dreamacro.github.io/clash/configuration/configuration-reference.html)
```
