### ISSUE TITLE
[BUG] docker 镜像 latest 标签并非最新稳定版，出现 segfault

### ISSUE THREAD

**Issue by shniubobo** [tindy2013/subconverter#659]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

tindy2013/subconverter:latest (13f5f734d6bc3f1824e04be2757f3f3cbcf2835571fc76070a4b504adb1b646a)

### 转换过程

clash 转换为 clash

### 转换设置

配置文件为默认，compose 文件如下：

```yaml
services:
  subconverter:
    image: tindy2013/subconverter:latest
    ports:
      - "25500:25500"
    restart: always
```

### 复现步骤

```
sudo docker compose up -d
sudo docker compose logs -f
```

然后访问`http://[省略]:25500/sub?target=clash&url=[省略]&list=true`

### 期望结果

latest 标签为 `README-docker.md` 中使用的版本，理解为推荐使用版本，即最新稳定版。访问上述地址应正常返回转换后的订阅。

### 实际结果

出现 segfault。若使用 `tindy2013/subconverter:0.8.1` 则无该问题。

根据 latest 镜像的上传时间推测对应的是最新 commit。目前没有任何标签对应的是“最新稳定版”这一概念，仅有“最新开发版”（latest）和“各历史及最新稳定版”（各版本号）。建议将标签方案更换为以下任意一种：

1. latest 对应最新 commit，stable 对应最新稳定版
2. latest 对应最新稳定版，next 对应最新 commit

### 错误信息

```shell
[包含过多敏感信息，省略先前部分]
subconverter-subconverter-1  | 2023/11/07 Tue 14:14:15.208125 [1 140115436653368][VERB] Parsing subscription data...
subconverter-subconverter-1 exited with code 139
```
