### ISSUE TITLE
[BUG] 最新的docker镜像部署后，生成的订阅链接在浏览器中会出现414的错误

### ISSUE THREAD

**Issue by real-jiakai** [tindy2013/subconverter#660]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

最新的docker镜像，tag: latest subconverter v0.8.1-bbcb643 backend

### 转换过程

订阅链接转clash

### 转换设置

远程配置：ACL4SSR_Online_Mini 精简版

### 复现步骤

1、docker-compose.yml的文件如下：

```yaml
version: '3.8'

services:
  subconverter:
    image: tindy2013/subconverter:latest
    container_name: subconverter
    restart: always
    ports:
      - "25500:25500"
```

2、订阅链接转换

3、生成的订阅链接在浏览器中会出现414的错误。

![image](https://github.com/tindy2013/subconverter/assets/82650452/5d71c87b-bf63-47f0-8bef-4fa1218ec770)

4、改用docker镜像tag为0.8.1，重新部署后端服务。

![image](https://github.com/tindy2013/subconverter/assets/82650452/456538b3-2a93-44cc-9c3e-f35c63989e53)

```yaml
version: '3.8'

services:
  subconverter:
    image: tindy2013/subconverter:0.8.1
    container_name: subconverter
    restart: always
    ports:
      - "25500:25500"
```

5、生成的订阅链接能成功在浏览器中展现。

### 期望结果

最新的docker镜像，起的服务作为后端地址，生成的订阅链接，放置在浏览器的地址栏不出现414错误。我也怀疑过是不是我的caddy反向代理服务器的问题，但我将后端地址由域名变更为ip地址:端口的形式，在浏览器的地址栏依旧得到414错误，因此这不是反向代理服务器的问题，应该是最新的docker镜像的问题。

由于我服务器上设置了watchtower，自动更新docker镜像，因此昨晚发布的最新docker镜像使得我今天无法获取订阅链接配置。

![image](https://github.com/tindy2013/subconverter/assets/82650452/61790833-bdf3-4f51-a22a-5add4090c273)

### 实际结果

生成的订阅链接是在浏览器中报414错误。

### 错误信息

```shell
日志信息里面涉及到节点信息，不方便提供，复现可以直接起一个docker容器，接着作为订阅转换的后端地址。
选择tag为latest的镜像生成的订阅链接会在浏览器中报错414，tag为0.8.1的镜像生成的订阅链接在浏览器中显示正常。

`我已经确认在最新Action编译的版本中复现 `这一项，我能力有限，无法复现。为了反馈bug，只好勾选一下。

作者复现的时候可以直接用这个网址：https://labs.play-with-docker.com/
运行`docker run -d --restart=always -p 25500:25500 tindy2013/subconverter:latest`
起了一个docker服务，接着将后端地址填写到订阅链接转换的后端地址。

后端地址类似这种形式：http://ip172-18-0-70-cl5na2efml8g00evevlg-25500.direct.labs.play-with-docker.com/sub?

最后生成的订阅链接在浏览器的地址栏打开，是414错误。
```
