### ISSUE TITLE
[BUG] <title> 在0.8.1版本中当url参数配置为 http://localhost/path  时不可用

### ISSUE THREAD

**Issue by Ch1cC** [tindy2013/subconverter#695]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

0.8.1

### 转换过程

v2ray转换为clash

### 转换设置

https://domain/sub?target=clash&new_name=true&url=http://localhost/path

### 复现步骤

https://domain/sub?target=clash&new_name=true&url=http://localhost/path

0.8.0 版本正常

### 期望结果

```
mixed-port: 7890
allow-lan: false
ipv6: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - localhost.ptlogin2.qq.com
```

### 实际结果

The following link doesn't contain any valid node info: http://localhost/path

### 错误信息

```shell
2023/12/28 Thu 20:54:03.293877 [149521 Thread-8][INFO] Fetching node data from url 'http://localhost/path'.
2023/12/28 Thu 20:54:06.275510 [149521 Thread-8][INFO] Fetching node data from url 'http://localhost/path'.
```
