### ISSUE TITLE
[BUG] !!PROVIDER= 参数在custom_proxy_group=部分组合筛选条件时出现错误

### ISSUE THREAD

**Issue by refined-fish** [tindy2013/subconverter#802]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

0.9.0 sub.xeton.dev后端

### 转换过程

clash订阅转换为clash订阅

### 转换设置

外部配置链接：https%3A%2F%2Fraw.githubusercontent.com%2Frefined-fish%2Fclash_rule_fish%2Frefs%2Fheads%2Fmain%2FFish_Rule.ini
这是我自己编辑的一份配置文件，其中内容参照本项目wiki书写

### 复现步骤

在外部配置链接模板中定义了
```
custom_proxy_group=🖐️ 手动切换`select`!!PROVIDER=main,backup
custom_proxy_group=🇭🇰 香港节点`url-test`!!PROVIDER=main,backup!!(港|HK|hk|Hong Kong|HongKong|hongkong)`http://www.gstatic.com/generate_204`30,,200

```
点击获取配置文件

### 期望结果

转换为
```
  - name: 🖐️ 手动切换
    type: select
    use:
      - main
      - backup
  
  - name: 🇭🇰 香港节点
   type: url-test
   url: http://www.gstatic.com/generate_204
   interval: 30
   tolerance: 200
   use:
     - main
     - backup
   filter: "港|HK|hk|Hong Kong|HongKong|hongkong"
```

### 实际结果

```
  - name: 🇭🇰 香港节点
   type: url-test
   url: http://www.gstatic.com/generate_204
   interval: 30
   tolerance: 200
   use:
     - main
     - backup!!(港|HK|hk|Hong Kong|HongKong|hongkong)
```

### 错误信息

```shell
转换成功完成，但不符合预期
```
