### ISSUE TITLE
[Feature] ruleset 转换的 rule-providers 的名称（expand=false情况下） ，可否将空格的URL 编码（%20 ）转换回空格

### ISSUE THREAD

**Issue by Se7enMuting** [tindy2013/subconverter#815]
### verify

- [X] 我已经仔细阅读[项目文档](https://github.com/tindy2013/subconverter/blob/master/README-cn.md)，确认现有功能无法解决我的需求
- [X] 我已经检索过现有[issue](https://github.com/tindy2013/subconverter/issues)，确认与现有issue的内容并不重复
- [X] 我已经尝试自行解决，确认自己没有能力解决

### 功能描述

`expand=false` 情况下
```
ruleset=大陆直连,clash-classic:https://raw.githubusercontent.com/dler-io/Rules/main/Clash/Provider/Domestic%20IPs.yaml
```
目前会转换成：
```
rule-providers:
  Domestic%20IPs:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/dler-io/Rules/main/Clash/Provider/Domestic%20IPs.yaml
    path: ./providers/rule-provider_Domestic%20IPs.yaml
    interval: 86400
```

### 可能的解决方案

希望可转换成：（%20 --> 空格）
```
rule-providers:
  Domestic IPs:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/dler-io/Rules/main/Clash/Provider/Domestic%20IPs.yaml
    path: ./providers/rule-provider_Domestic IPs.yaml
    interval: 86400
```
