### ISSUE TITLE
pref.yml中设置的default_url不生效

### ISSUE THREAD

**Issue by Jet-coco** [tindy2013/subconverter#96]
#80 情况类似，在pref.yml中设置了default_url，但是请求失败，返回“Invalid request!”。
请问一下是不是我的yml文件填写格式错了？

pref.yml配置：
```  
common:  
  api_mode: true  
  api_access_token: password  
  default_url: ["https://xxx"] 
```

version: 0.4.4
